[package]
name = "displaydoc"
version = "0.1.2"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/yaahc/displaydoc"
homepage = "https://github.com/yaahc/displaydoc"
documentation = "https://docs.rs/displaydoc/0.1.0/displaydoc"
keywords = ["display", "derive"]
description = """
A derive macro for implementing the display Trait via a doc comment and string interpolation
"""

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
